export const paintings = [
  {
    id: 1,
    name: "The price of Love",
    author: "Chris Wool",
    price: 1500,
    img: "/images/image1.jpg",
    numberOfUnits: 1,
    category: "Modern Art",
  },
  {
    id: 2,
    name: "Lost in my thoughts",
    author: "Peter Doig",
    price: 200,
    img: "/images/image2.jpg",
    numberOfUnits: 1,
    category: "Surrealism",
  },
  {
    id: 3,
    name: "Fame",
    author: "Damien Hirst",
    price: 2450,
    img: "/images/image3.jpg",
    numberOfUnits: 1,
    category: "Modern Art",
  },
  {
    id: 4,
    name: "Scared",
    author: "Richard Prince",
    price: 100,
    img: "/images/image4.jpg",
    numberOfUnits: 1,
    category: "Abstract",
  },
  {
    id: 5,
    name: "To my brother",
    author: "Anselm Kiefer",
    price: 190,
    img: "/images/image5.jpg",
    numberOfUnits: 1,
    category: "Surrealism",
  },
  {
    id: 6,
    name: "Highest in the room",
    author: "Adrian Ghenie",
    price: 500,
    img: "/images/image6.jpg",
    numberOfUnits: 1,
    category: "Abstract",
  },
  {
    id: 7,
    name: "Lucid Dreams",
    author: "Mark Grotjahn",
    price: 175,
    img: "/images/image7.jpg",
    numberOfUnits: 1,
    category: "Surrealism",
  },
  {
    id: 8,
    name: "Beauty and the beast",
    author: "Rudolf Stingel",
    price: 450,
    img: "/images/image8.jpg",
    numberOfUnits: 1,
    category: "Modern Art",
  },
  {
    id: 9,
    name: "Memories",
    author: "Zeng Fanzhi",
    price: 1200,
    img: "/images/image9.jpg",
    numberOfUnits: 1,
    category: "Abstract",
  },
  {
    id: 10,
    name: "Lonely",
    author: "Yoshitomo Nara",
    price: 80,
    img: "/images/image10.jpg",
    numberOfUnits: 1,
    category: "Abstract",
  },
];

export const steps = [
  "Account information",
  "Personal Details",
  "Payment",
  "Complete",
];

export const slides = [
  {
    title: "30% Sale On Everything Only NOW",
    img: "/images/image1.jpg",
  },
  {
    title: "Damien Hirst Special Collection Out NOW",
    img: "/images/image2.jpg",
  },
  {
    title: "Save Up To 20% And Become Member",
    img: "/images/image3.jpg",
  },
];
