export const paintings = [
  {
    id: 1,
    name: "The price of Love",
    author: "Christopher Wool",
    price: 1500,
    img: "/images/image1.jpg",
  },
  {
    id: 2,
    name: "Lost in my thoughts",
    author: "Peter Doig",
    price: 200,
    img: "/images/image2.jpg",
  },
  {
    id: 3,
    name: "Fame",
    author: "Damien Hirst",
    price: 2450,
    img: "/images/image3.jpg",
  },
  {
    id: 4,
    name: "Scared",
    author: "Richard Prince",
    price: 100,
    img: "/images/image4.jpg",
  },
  {
    id: 5,
    name: "To my brother",
    author: "Anselm Kiefer",
    price: 190,
    img: "/images/image5.jpg",
  },
  {
    id: 6,
    name: "Highest in the room",
    author: "Adrian Ghenie",
    price: 500,
    img: "/images/image6.jpg",
  },
  {
    id: 7,
    name: "Lucid Dreams",
    author: "Mark Grotjahn",
    price: 175,
    img: "/images/image7.jpg",
  },
  {
    id: 8,
    name: "Beauty and the beast",
    author: "Rudolf Stingel",
    price: 450,
    img: "/images/image8.jpg",
  },
  {
    id: 9,
    name: "Memories",
    author: "Zeng Fanzhi",
    price: 1200,
    img: "/images/image9.jpg",
  },
  {
    id: 10,
    name: "Lonely",
    author: "Yoshitomo Nara",
    price: 80,
    img: "/images/image10.jpg",
  },
];
