export const paintings = [
  {
    id: 1,
    name: "The price of Love",
    author: "Chris Wool",
    price: 1500,
    img: "/images/image1.jpg",
    description:
      "This painting has been painstakingly made with a mix of carefully blended acrylic colours using paintbrushes and also my pallet knife textures in a lot of it too. Created on a square canvas measuring just under 40 cm x 40 cm and 1.5 cm deep. It is strung at the back so it can simply be hung as it is.",
    numberOfUnits: 1,
    category: "Modern Art",
    poster1Light: "/images/posters/poster1-img1-light.jpg",
    poster2Light: "/images/posters/poster2-img1-light.jpg",
    poster3Light: "/images/posters/poster3-img1-light.jpg",
    poster4Light: "/images/posters/poster4-img1-light.jpg",
    poster1Dark: "/images/posters/poster1-img1-dark.jpg",
    poster2Dark: "/images/posters/poster2-img1-dark.jpg",
    poster3Dark: "/images/posters/poster3-img1-dark.jpg",
    poster4Dark: "/images/posters/poster4-img1-dark.jpg",
  },
  {
    id: 2,
    name: "Lost in thoughts",
    author: "Peter Doig",
    price: 200,
    img: "/images/image2.jpg",
    description:
      "These deep canvases will sit flush against the wall on a nail or wall bracket. Painted white on the canvas edges, which really helps make the colours and textures 'pop' it is also varnished in a professional glossy varnish. Varnished in a glossy varnish, strung at the back for hanging and painted black on the canvas edges. This artwork, as always comes with a certificate of authenticity.",
    numberOfUnits: 1,
    category: "Surrealism",
    poster1Light: "/images/posters/poster1-img2-light.jpg",
    poster2Light: "/images/posters/poster2-img2-light.jpg",
    poster3Light: "/images/posters/poster3-img2-light.jpg",
    poster4Light: "/images/posters/poster4-img2-light.jpg",
    poster1Dark: "/images/posters/poster1-img2-dark.jpg",
    poster2Dark: "/images/posters/poster2-img2-dark.jpg",
    poster3Dark: "/images/posters/poster3-img2-dark.jpg",
    poster4Dark: "/images/posters/poster4-img2-dark.jpg",
  },
  {
    id: 3,
    name: "Fame",
    author: "Damien Hirst",
    price: 2450,
    img: "/images/image3.jpg",
    description:
      "The artwork was a study of light and shadow and a more minimal approach to the subject matter utilizing, light, shadow and simple shape. The result is a powerful, striking contemplation of roses. The bold colours make this art uplifting and strong. Painted on canvas that is strung at the back ready for hanging. The canvas has also been varnished in a gloss UV protection varnish for protection.",
    numberOfUnits: 1,
    category: "Modern Art",
    poster1Light: "/images/posters/poster1-img3-light.jpg",
    poster2Light: "/images/posters/poster2-img3-light.jpg",
    poster3Light: "/images/posters/poster3-img3-light.jpg",
    poster4Light: "/images/posters/poster4-img3-light.jpg",
    poster1Dark: "/images/posters/poster1-img3-dark.jpg",
    poster2Dark: "/images/posters/poster2-img3-dark.jpg",
    poster3Dark: "/images/posters/poster3-img3-dark.jpg",
    poster4Dark: "/images/posters/poster4-img3-dark.jpg",
  },
  {
    id: 4,
    name: "Scared",
    author: "Richard Prince",
    price: 100,
    img: "/images/image4.jpg",
    description:
      "This art has been created using lots of texture and interesting aspects of colour using very thick paint, but it also has areas of silver leafing work in the vase and the background which makes it even more luxurious when the light catches it. Framed in a luxury white wooden frame that has grain detail in it and strung at the back ready for hanging.",
    numberOfUnits: 1,
    category: "Abstract",
    poster1Light: "/images/posters/poster1-img4-light.jpg",
    poster2Light: "/images/posters/poster2-img4-light.jpg",
    poster3Light: "/images/posters/poster3-img4-light.jpg",
    poster4Light: "/images/posters/poster4-img4-light.jpg",
    poster1Dark: "/images/posters/poster1-img4-dark.jpg",
    poster2Dark: "/images/posters/poster2-img4-dark.jpg",
    poster3Dark: "/images/posters/poster3-img4-dark.jpg",
    poster4Dark: "/images/posters/poster4-img4-dark.jpg",
  },
  {
    id: 5,
    name: "To my brother",
    author: "Anselm Kiefer",
    price: 190,
    img: "/images/image5.jpg",
    description:
      "Very tactile, (the depth and texture to the paint is lost somewhat in photographs) varnished in a gloss varnish to protect the colours. Pop art meets surrealism in this modern canvas art. The edges are painted in a turquoise shade and it is strung at the back for hanging. It has also been varnished in a UV protective, slightly glossy varnish.",
    numberOfUnits: 1,
    category: "Surrealism",
    poster1Light: "/images/posters/poster1-img5-light.jpg",
    poster2Light: "/images/posters/poster2-img5-light.jpg",
    poster3Light: "/images/posters/poster3-img5-light.jpg",
    poster4Light: "/images/posters/poster4-img5-light.jpg",
    poster1Dark: "/images/posters/poster1-img10-dark.jpg",
    poster2Dark: "/images/posters/poster2-img5-dark.jpg",
    poster3Dark: "/images/posters/poster3-img5-dark.jpg",
    poster4Dark: "/images/posters/poster4-img5-dark.jpg",
  },
  {
    id: 6,
    name: "Highest in the room",
    author: "Adrian Ghenie",
    price: 500,
    img: "/images/image6.jpg",
    poster1Light: "/images/posters/poster1-img6-light.jpg",
    poster2Light: "/images/posters/poster2-img6-light.jpg",
    poster3Light: "/images/posters/poster3-img6-light.jpg",
    poster4Light: "/images/posters/poster4-img6-light.jpg",
    poster1Dark: "/images/posters/poster1-img6-dark.jpg",
    poster2Dark: "/images/posters/poster2-img6-dark.jpg",
    poster3Dark: "/images/posters/poster3-img6-dark.jpg",
    poster4Dark: "/images/posters/poster4-img6-dark.jpg",
    description:
      "Painted on thick watercolour paper. It is A4 in size and so it's ideal to pop into a frame of your choice. The acrylic paints have been varnished with a professional artists varnish for protection. Provided with a certificate of authenticity. The materials used in this artwork are acrylics on thick watercolour paper.",
    numberOfUnits: 1,
    category: "Abstract",
  },
  {
    id: 7,
    name: "Lucid Dreams",
    author: "Mark Grotjahn",
    price: 175,
    img: "/images/image7.jpg",
    poster1Light: "/images/posters/poster1-img7-light.jpg",
    poster2Light: "/images/posters/poster2-img7-light.jpg",
    poster3Light: "/images/posters/poster3-img7-light.jpg",
    poster4Light: "/images/posters/poster4-img7-light.jpg",
    poster1Dark: "/images/posters/poster1-img7-dark.jpg",
    poster2Dark: "/images/posters/poster2-img7-dark.jpg",
    poster3Dark: "/images/posters/poster3-img7-dark.jpg",
    poster4Dark: "/images/posters/poster4-img7-dark.jpg",
    description:
      "Varnished in a glossy varnish with UV protection to preserve my colours and supplied with a certificate of authenticity for future provenance. This piece is framed in a broad, luxurious high quality wooden frame that is strung at the back, ready for hanging. Size: 15.75 x 11.75 inches (Unframed) 21.5 x 17.5 x 1.5 inches (Framed). Materials used: art modelling clay and acrilics",
    numberOfUnits: 1,
    category: "Surrealism",
  },
  {
    id: 8,
    name: "Beauty and the beast",
    author: "Rudolf Stingel",
    price: 450,
    img: "/images/image8.jpg",
    description:
      "In abstract style, this particular piece reflects on the energy of a seascape as the wet of the sky meets the great ocean. Using blending techniques and pallet knives too, this art is very soothing and full of calming energy. Strung at the back and supplied with a certificate of authenticity, it is also varnished in a gloss varnish for protection.",
    numberOfUnits: 1,
    category: "Modern Art",
    poster1Light: "/images/posters/poster1-img8-light.jpg",
    poster2Light: "/images/posters/poster2-img8-light.jpg",
    poster3Light: "/images/posters/poster3-img8-light.jpg",
    poster4Light: "/images/posters/poster4-img8-light.jpg",
    poster1Dark: "/images/posters/poster1-img8-dark.jpg",
    poster2Dark: "/images/posters/poster2-img8-dark.jpg",
    poster3Dark: "/images/posters/poster3-img8-dark.jpg",
    poster4Dark: "/images/posters/poster4-img8-dark.jpg",
  },
  {
    id: 9,
    name: "Memories",
    author: "Zeng Fanzhi",
    price: 1200,
    img: "/images/image9.jpg",
    description:
      "Hand created with thick acrylics and pallet knives, which give a super textured look and feel to the art. Bright and colourful and framed in a mahogany coloured wooden frame (the expense of framing reflected in the price). There is no glass in the frame so the thick textures can be fully appreciated. Complete with a certificate of authenticity and each is strung at the back, ready for hanging.",
    numberOfUnits: 1,
    category: "Abstract",
    poster1Light: "/images/posters/poster1-img9-light.jpg",
    poster2Light: "/images/posters/poster2-img9-light.jpg",
    poster3Light: "/images/posters/poster3-img9-light.jpg",
    poster4Light: "/images/posters/poster4-img9-light.jpg",
    poster1Dark: "/images/posters/poster1-img9-dark.jpg",
    poster2Dark: "/images/posters/poster2-img9-dark.jpg",
    poster3Dark: "/images/posters/poster3-img9-dark.jpg",
    poster4Dark: "/images/posters/poster4-img9-dark.jpg",
  },
  {
    id: 10,
    name: "Lonely",
    author: "Yoshitomo Nara",
    price: 80,
    img: "/images/image10.jpg",
    description:
      "An abstract, textured, small painting. This artwork has a graffiti feel to it, yet it is made using thick acrylic paints to roughly mask out the characters, which have then been outlined with thick black lines. Unframed and varnished to bring out the lovely textures. Supplied with a certificate of authenticity. Materials used: Acrilics on board.",
    numberOfUnits: 1,
    category: "Abstract",
    poster1Light: "/images/posters/poster1-img10-light.jpg",
    poster2Light: "/images/posters/poster2-img10-light.jpg",
    poster3Light: "/images/posters/poster3-img10-light.jpg",
    poster4Light: "/images/posters/poster4-img10-light.jpg",
    poster1Dark: "/images/posters/poster1-img10-dark.jpg",
    poster2Dark: "/images/posters/poster2-img10-dark.jpg",
    poster3Dark: "/images/posters/poster3-img10-dark.jpg",
    poster4Dark: "/images/posters/poster4-img10-dark.jpg",
  },
];

export const steps = ["Personal Details", "Payment", "Complete"];

export const slides = [
  {
    title: "30% Sale On Everything Only NOW",
    img: "/images/image1.jpg",
  },
  {
    title: "Damien Hirst Special Collection Out NOW",
    img: "/images/image2.jpg",
  },
  {
    title: "Save Up To 20% And Become Member",
    img: "/images/image3.jpg",
  },
];
